#pragma once
#define BLACK		0
#define WHITE		1
#define MAXDEPTH	20
#define HASHSIZE	30000
#define UPPERLIMIT	30000
#define LOWERLIMIT	-30000
#define MATE		30000
#define CONTEMPT	-1000
#define SPACES		64
#define WIDTH		8
#define NORTH		-8
#define SOUTH		8
#define EAST		1
#define WEST		-1
#define NORTHEAST	-7
#define NORTHWEST	-9
#define SOUTHEAST	9
#define SOUTHWEST	7
#define KING		20005
#define QUEEN		904
#define ROOK		503
#define BISHOP		322
#define KNIGHT		301
#define PAWN		100
#define KINDEX		5
#define QINDEX		4
#define RINDEX		3
#define BINDEX		2
#define NINDEX		1
#define PINDEX		0
#define EMPTY		0
#define STANDARD	0
#define DOUBLEPUSH	1
#define KCASTLE		2
#define QCASTLE		3
#define CAPTURE		4
#define ENPASSANT	5
#define NULLMOVE	6
#define FAIL		7	
#define PROMOTE		8
#define NPROMOTE	8
#define BPROMOTE	9
#define RPROMOTE	10
#define QPROMOTE	11
#define PROMOTEC	12
#define NPROMOTEC	12
#define BPROMOTEC	13
#define RPROMOTEC	14
#define QPROMOTEC	15
#define MEMORY		255
#define STARTFEN	"rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"